name: Bug report
description: Report a reproducible bug in the app
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Issues without **clear reproduction steps** may be closed.

  - type: input
    id: app_version
    attributes:
      label: App version
      placeholder: e.g. 1.3.0 (Android) / TestFlight build 42
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Android
        - iOS
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: OS version
      placeholder: e.g. Android 14 / iOS 17.2
    validations:
      required: true

  - type: dropdown
    id: backend
    attributes:
      label: Backend
      options:
        - Jellyfin
        - Navidrome
        - Both
        - Not applicable
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to …
        2. Tap …
        3. Observe …
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Attach logs, screenshots, or screen recordings if relevant.
