name: Documentation issue
description: Report missing or incorrect documentation
labels: ["documentation"]
body:
  - type: textarea
    id: location
    attributes:
      label: Documentation location
      placeholder: README, onboarding screen, settings view, etc.
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What is wrong or missing?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested improvement

